server:
  port: 8090
  address: localhost
spring:
  application.name: room-service

  kafka:
    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: app.groopy.roomservice.infrastructure.kafka.RoomServiceKafkaDeserializer

elasticsearch:
  host: localhost
  port: 9200

grpc:
  server:
    port: 8070
    security:
      enabled: true