spring:
  application.name: wall-service
  data:
    mongodb:
      uri: mongodb+srv://root:root@localhost/?authMechanism=DEFAULT&authSource=expat-db?retryWrites=true&w=majority

grpc:
  server:
    port: 8070
    security:
      enabled: false
  client:
    chatService:
      address: "static://localhost:8072"
      negotiationType: PLAINTEXT
