spring:
  application.name: wall-service
  data:
    mongodb:
      uri: ${MONGO_DB_URI}

grpc:
  server:
    port: 8070
    security:
      enabled: false
  client:
    chatService:
      address: "static://chatservice:8072"
      negotiationType: PLAINTEXT
