spring:
  application.name: wall-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PWD}@${MONGO_DB_HOST}/${MONGO_HUB}?retryWrites=true&w=majority

grpc:
  server:
    port: 8070
    security:
      enabled: false
  client:
    chatService:
      address: "static://chatservice:8072"
      negotiationType: PLAINTEXT
