server:
  port: 8090
spring:
  application.name: wall-service

  kafka:
    bootstrap-servers: kafka:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: app.groopy.wallservice.infrastructure.kafka.WallServiceKafkaDeserializer

elasticsearch:
  host: elasticsearch
  port: 9200

grpc:
  server:
    port: 8070
    security:
      enabled: false